### ISSUE TITLE
Max4Live devices : Text is barely visible

### ISSUE THREAD

**Issue by simonperrier11** [MagistraNocte/Max-8-Default-Dark-Mode#4]
Hi, 

Thank you for this awesome theme. Currently, the labels for Max4Live devices (live.slider, live.arrows, etc.) are kind of hard to see while using the dark theme. AFAIK they are also available to MaxMSP without Live.

<img width="885" alt="Screenshot 2023-11-16 at 10 00 28" src="https://github.com/MagistraNocte/Max-8-Default-Dark-Mode/assets/44238249/21a880f3-b918-4332-a0de-ec1a03e55f97">

**Comment by MagistraNocte** [comment]
Hi, unfortunately from my research it seems like the live objects text color is an hard-coded value and cannot be changed from a theme
